In [3]:
import numpy as np # numpy: 배열 다루기에 특화

my_list = list(range(1000000))
my_array = np.arange(1000000)

In [4]:
%timeit my_list2 = [i * 2 for i in my_list]
%timeit my_array2 = my_array * 2

55 ms ± 2.75 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.98 ms ± 105 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
a = [
    [1, 2.3, 3],
    [-123, 123, 0]
] # 2차원 리스트: 리스트 안에 리스트
data = np.array(a)
print(data) # 데이터 형태를 비슷하게 바꿔줌

[[   1.     2.3    3. ]
 [-123.   123.     0. ]]


In [8]:
# 0차원: 스칼라(scala), 1차원: 벡터(vector), 
# 2차원: 행렬(matrix), 3차원: 텐서(tenser)
print(data * 10)
print(data + data)

[[   10.    23.    30.]
 [-1230.  1230.     0.]]
[[   2.     4.6    6. ]
 [-246.   246.     0. ]]


In [9]:
print(data.shape) # 가장 큰 배열 2개, 그 안의 배열 3개/ 2행 3열
print(data.dtype)

(2, 3)
float64


## ndarray 생성하기

*n차원의 배열*

In [12]:
data1 = [1, 2, 3, 4, 5]
arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [16]:
arr2 = np.array([[1.1, 2.2], [3.3, 4.4]])
print(arr2)
print(type(arr2))

[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [17]:
arr2 = np.array([[1.1, 2.2], [3.3, 4.4, 5.5]]) # error

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [14]:
print(arr1.ndim) # 1차원
print(arr2.ndim) # 2차원

1
2


In [15]:
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 2)


In [21]:
print([0] * 10) # 위랑 아래는 똑같은데...
print(np.zeros(10))
print(np.zeros((5, 5)))
print(np.empty((2, 2, 2)))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [23]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


## ndarray 자료형

In [25]:
arr1 = np.array([1, 2, 3], dtype=np.float64) # 생성할 때 속성을 넣어서 형변환
arr2 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [27]:
arr1 = np.array([1, 2, 3])
print(arr1.dtype)
float_arr1 = arr1.astype(np.float64) # 명시적 형변환
print(float_arr1)
print(float_arr1.dtype)

int64
[1. 2. 3.]
float64


In [28]:
arr2 = np.array([1.1, 2.2, 3.3, 9.9])
print(arr2.dtype)
int_arr2 = arr2.astype(np.int64) # 형변환 시 소수점 버림
print(int_arr2)
print(int_arr2.dtype) 

float64
[1 2 3 9]
int64


## 산술 연산

In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr) # 2 * 3 shape
print(arr * arr) # 같은 위치에 있는 데이터끼리 사칙연산
print(arr + arr)
print(1 / arr)
print(arr ** 3)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]


In [35]:
arr2 = np.array([[3, 2, 1], [1, 2, 3]])
print(arr)
print(arr2)
print(arr > arr2)
print(arr == 3)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [1 2 3]]
[[False False  True]
 [ True  True  True]]
[[False False  True]
 [False False False]]


## 색인(인덱싱)과 슬라이싱

In [36]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [39]:
print(arr[5])
print(arr[2:5])

5
[2 3 4]


In [40]:
arr[2:5] = 10
print(arr) # 원본이 변함

[ 0  1 10 10 10  5  6  7  8  9]


In [41]:
py_list = [1, 2, 3, 4, 5]
py_list[2:3].pop()
print(py_list) # 원본은 그대로

[1, 2, 3, 4, 5]


In [42]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [44]:
print(arr[1][1])
print(arr[1, 1])

5
5


In [48]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
          [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
          [[11, 22, 33], [44, 55, 66], [77, 88, 99]]])

In [53]:
print(arr3d[2][0][1])
print(arr3d[2, 0, 1])

22
22


In [57]:
arr3d[:1, 1:, 2:] # 슬라이싱 접근 대괄호 유지

array([[[6],
        [9]]])

In [58]:
arr3d[0, 1:, 2:] # 인덱스 접근 대괄호가 하나 줄어듦

array([[6],
       [9]])

In [59]:
arr3d[0, 1:, 2:] = 9999
print(arr3d)

[[[   1    2    3]
  [   4    5 9999]
  [   7    8 9999]]

 [[  11   12   13]
  [  14   15   16]
  [  17   18   19]]

 [[  11   22   33]
  [  44   55   66]
  [  77   88   99]]]


## 불리언 값으로 선택

In [61]:
names = np.array(['hong', 'kim', 'hong', 'kim'])
data = np.array([['math', 60], ['math', 90], ['eng', 70], ['eng', 50]])

In [65]:
names == 'hong'

array([ True, False,  True, False])

In [66]:
data[[True, False, True, False]]

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [64]:
data[names == 'hong'] # 특정 조건에 맞는 데이터를 고를 때

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [68]:
print(data[names == 'hong', 1]) # 인덱스 접근
print(data[names == 'hong', :1]) # 슬라이싱 -> 데이터 구조가 다름

['60' '70']
[['math']
 ['eng']]


In [74]:
print(names != 'hong')
print(~(names == 'hong'))

[False  True False  True]
[False  True False  True]


In [75]:
cond = names == 'kim'
data[cond]

array([['math', '90'],
       ['eng', '50']], dtype='<U21')

## 팬시 색인 (fancy indexing)

In [79]:
arr = np.zeros((8, 4))

for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [80]:
arr[[4, 3, 0, 5]] # 대괄호 안에 대괄호 -> 내가 원하는 행을 직접 고를 수 있음

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [81]:
arr[[-3, -5, -1]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [89]:
arr = np.arange(32).reshape(8, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [90]:
print(arr[[1, 5], [2, 3]])

[ 6 23]


In [92]:
arr[[1, 5]][:, [2, 3]]

array([[ 6,  7],
       [22, 23]])

## 배열 전치

In [95]:
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [96]:
print(arr.T) # 축을 바꿀 때

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [100]:
# 행렬의 내적, 곱 연산
print(arr @ arr.T)
print(np.dot(arr, arr.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


## numpy 함수

In [101]:
samples = np.random.standard_normal(size=(3, 3))
print(samples)

[[ 1.8257906   2.13267814 -1.46867918]
 [ 0.23357155  0.50990307 -0.66155212]
 [-1.20844597 -0.97724701 -0.29620833]]


In [103]:
arr1 = np.sqrt(samples) # nan: not a number -> 루트를 씌웠는데 음수일 때/ 결측치
print(arr1)

[[1.35121819 1.46036918        nan]
 [0.48329241 0.71407497        nan]
 [       nan        nan        nan]]


C:\Users\1-14\AppData\Local\Temp\ipykernel_15632\986832208.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr1 = np.sqrt(samples) # nan: not a number -> 루트를 씌웠는데 음수일 때/ 결측치


In [104]:
arr2 = np.abs(samples) # absolute: 절댓값
print(arr2)

[[1.8257906  2.13267814 1.46867918]
 [0.23357155 0.50990307 0.66155212]
 [1.20844597 0.97724701 0.29620833]]


In [105]:
np.isnan(arr1)

array([[False, False,  True],
       [False, False,  True],
       [ True,  True,  True]])