In [2]:
import numpy as np
arr = np.arange(32).reshape(8, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [5]:
arr[[1, 5]][:, [2,3]]

array([[ 6,  7],
       [22, 23]])