In [2]:
import numpy as np
arr = np.arange(32).reshape(8, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [5]:
arr[[1, 5]][:, [2,3]]

array([[ 6,  7],
       [22, 23]])

In [1]:
import pandas as cd
import seaborn as sns

In [2]:
df = sns.load_dataset('penguins')

In [3]:
df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
3            NaN     NaN  
4         3450.0  Female  
..           ...     ...  
339          NaN     NaN  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[344 rows x 7 columns]

In [4]:
dfc = df.copy()

In [5]:
dfc

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
3            NaN     NaN  
4         3450.0  Female  
..           ...     ...  
339          NaN     NaN  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[344 rows x 7 columns]

In [7]:
dfc['species'].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [9]:
dfc.shape

(344, 7)

In [11]:
dfc.index

RangeIndex(start=0, stop=344, step=1)

In [12]:
dfc.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [13]:
dfc.values

array([['Adelie', 'Torgersen', 39.1, ..., 181.0, 3750.0, 'Male'],
       ['Adelie', 'Torgersen', 39.5, ..., 186.0, 3800.0, 'Female'],
       ['Adelie', 'Torgersen', 40.3, ..., 195.0, 3250.0, 'Female'],
       ...,
       ['Gentoo', 'Biscoe', 50.4, ..., 222.0, 5750.0, 'Male'],
       ['Gentoo', 'Biscoe', 45.2, ..., 212.0, 5200.0, 'Female'],
       ['Gentoo', 'Biscoe', 49.9, ..., 213.0, 5400.0, 'Male']],
      shape=(344, 7), dtype=object)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [15]:
dfc

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
3            NaN     NaN  
4         3450.0  Female  
..           ...     ...  
339          NaN     NaN  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[344 rows x 7 columns]

In [16]:
df.sort_index(ascending=False)

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
343  Gentoo     Biscoe            49.9           16.1              213.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
340  Gentoo     Biscoe            46.8           14.3              215.0   
339  Gentoo     Biscoe             NaN            NaN                NaN   
..      ...        ...             ...            ...                ...   
4    Adelie  Torgersen            36.7           19.3              193.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
2    Adelie  Torgersen            40.3           18.0              195.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
0    Adelie  Torgersen            39.1           18.7              181.0   

     body_mass_g     sex  
343       5400.0    Male  
342       5200.0  Female  
341       5750.0    Male  
340       4850.0  Female  
339          NaN     NaN  
..           ...     ...  
4         3450.0  Female  
3            NaN     NaN  
2         3250.0  Female  
1         3800.0  Female  
0         3750.0    Male  

[344 rows x 7 columns]

In [17]:
dfc.sort_values('body_mass_g')

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
190  Chinstrap      Dream            46.9           16.6              192.0   
58      Adelie     Biscoe            36.5           16.6              181.0   
64      Adelie     Biscoe            36.4           17.1              184.0   
54      Adelie     Biscoe            34.5           18.1              187.0   
116     Adelie  Torgersen            38.6           17.0              188.0   
..         ...        ...             ...            ...                ...   
337     Gentoo     Biscoe            48.8           16.2              222.0   
253     Gentoo     Biscoe            59.6           17.0              230.0   
237     Gentoo     Biscoe            49.2           15.2              221.0   
3       Adelie  Torgersen             NaN            NaN                NaN   
339     Gentoo     Biscoe             NaN            NaN                NaN   

     body_mass_g     sex  
190       2700.0  Female  
58        2850.0  Female  
64        2850.0  Female  
54        2900.0  Female  
116       2900.0  Female  
..           ...     ...  
337       6000.0    Male  
253       6050.0    Male  
237       6300.0    Male  
3            NaN     NaN  
339          NaN     NaN  

[344 rows x 7 columns]

In [18]:
df.sort_values('island')

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
343  Gentoo     Biscoe            49.9           16.1              213.0   
108  Adelie     Biscoe            38.1           17.0              181.0   
109  Adelie     Biscoe            43.2           19.0              197.0   
110  Adelie     Biscoe            38.1           16.5              198.0   
111  Adelie     Biscoe            45.6           20.3              191.0   
..      ...        ...             ...            ...                ...   
72   Adelie  Torgersen            39.6           17.2              196.0   
71   Adelie  Torgersen            39.7           18.4              190.0   
70   Adelie  Torgersen            33.5           19.0              190.0   
68   Adelie  Torgersen            35.9           16.6              190.0   
0    Adelie  Torgersen            39.1           18.7              181.0   

     body_mass_g     sex  
343       5400.0    Male  
108       3175.0  Female  
109       4775.0    Male  
110       3825.0  Female  
111       4600.0    Male  
..           ...     ...  
72        3550.0  Female  
71        3900.0    Male  
70        3600.0  Female  
68        3050.0  Female  
0         3750.0    Male  

[344 rows x 7 columns]

In [19]:
dfc.sort_values(['bill_length_mm', 'bill_depth_mm'])

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
142     Adelie      Dream            32.1           15.5              188.0   
98      Adelie      Dream            33.1           16.1              178.0   
70      Adelie  Torgersen            33.5           19.0              190.0   
92      Adelie      Dream            34.0           17.1              185.0   
8       Adelie  Torgersen            34.1           18.1              193.0   
..         ...        ...             ...            ...                ...   
321     Gentoo     Biscoe            55.9           17.0              228.0   
169  Chinstrap      Dream            58.0           17.8              181.0   
253     Gentoo     Biscoe            59.6           17.0              230.0   
3       Adelie  Torgersen             NaN            NaN                NaN   
339     Gentoo     Biscoe             NaN            NaN                NaN   

     body_mass_g     sex  
142       3050.0  Female  
98        2900.0  Female  
70        3600.0  Female  
92        3400.0  Female  
8         3475.0     NaN  
..           ...     ...  
321       5600.0    Male  
169       3700.0  Female  
253       6050.0    Male  
3            NaN     NaN  
339          NaN     NaN  

[344 rows x 7 columns]

In [20]:
# 5000g 이상의 펭귄 출력

In [21]:
cond1 = dfc['body_mass_g'] >= 5000
dfc.loc[cond1]

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
221  Gentoo  Biscoe            50.0           16.3              230.0   
223  Gentoo  Biscoe            50.0           15.2              218.0   
224  Gentoo  Biscoe            47.6           14.5              215.0   
227  Gentoo  Biscoe            46.7           15.3              219.0   
229  Gentoo  Biscoe            46.8           15.4              215.0   
..      ...     ...             ...            ...                ...   
335  Gentoo  Biscoe            55.1           16.0              230.0   
337  Gentoo  Biscoe            48.8           16.2              222.0   
341  Gentoo  Biscoe            50.4           15.7              222.0   
342  Gentoo  Biscoe            45.2           14.8              212.0   
343  Gentoo  Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
221       5700.0    Male  
223       5700.0    Male  
224       5400.0    Male  
227       5200.0    Male  
229       5150.0    Male  
..           ...     ...  
335       5850.0    Male  
337       6000.0    Male  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[67 rows x 7 columns]

In [22]:
# Gentoo종의 flipper_length 평균

In [24]:
cond2 = dfc['species'] == 'Gentoo'
dfc.loc[cond2, 'flipper_length_mm'].mean()

np.float64(217.1869918699187)

In [25]:
# Female Chinstrap종의 bill_length 높은순 정렬

In [28]:
cond3 = dfc['species'] == 'Chinstrap'
cond4 = dfc['sex'] == 'Female'

dfc.loc[cond3 & cond4].sort_values('bill_length_mm', ascending=False)

species island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
169  Chinstrap  Dream            58.0           17.8              181.0   
196  Chinstrap  Dream            50.9           17.9              196.0   
178  Chinstrap  Dream            50.5           18.4              200.0   
219  Chinstrap  Dream            50.2           18.7              198.0   
198  Chinstrap  Dream            50.1           17.9              190.0   
201  Chinstrap  Dream            49.8           17.3              198.0   
202  Chinstrap  Dream            48.1           16.4              199.0   
188  Chinstrap  Dream            47.6           18.3              195.0   
187  Chinstrap  Dream            47.5           16.8              199.0   
164  Chinstrap  Dream            47.0           17.3              185.0   
190  Chinstrap  Dream            46.9           16.6              192.0   
213  Chinstrap  Dream            46.8           16.5              189.0   
176  Chinstrap  Dream            46.7           17.9              195.0   
162  Chinstrap  Dream            46.6           17.8              193.0   
152  Chinstrap  Dream            46.5           17.9              192.0   
180  Chinstrap  Dream            46.4           17.8              191.0   
170  Chinstrap  Dream            46.4           18.6              190.0   
193  Chinstrap  Dream            46.2           17.5              187.0   
158  Chinstrap  Dream            46.1           18.2              178.0   
160  Chinstrap  Dream            46.0           18.9              195.0   
166  Chinstrap  Dream            45.9           17.1              190.0   
214  Chinstrap  Dream            45.7           17.0              195.0   
204  Chinstrap  Dream            45.7           17.3              193.0   
211  Chinstrap  Dream            45.6           19.4              194.0   
195  Chinstrap  Dream            45.5           17.0              196.0   
155  Chinstrap  Dream            45.4           18.7              188.0   
157  Chinstrap  Dream            45.2           17.8              198.0   
208  Chinstrap  Dream            45.2           16.6              191.0   
216  Chinstrap  Dream            43.5           18.1              202.0   
174  Chinstrap  Dream            43.2           16.6              187.0   
184  Chinstrap  Dream            42.5           16.7              187.0   
206  Chinstrap  Dream            42.5           17.3              187.0   
172  Chinstrap  Dream            42.4           17.3              181.0   
182  Chinstrap  Dream            40.9           16.6              187.0   

     body_mass_g     sex  
169       3700.0  Female  
196       3675.0  Female  
178       3400.0  Female  
219       3775.0  Female  
198       3400.0  Female  
201       3675.0  Female  
202       3325.0  Female  
188       3850.0  Female  
187       3900.0  Female  
164       3700.0  Female  
190       2700.0  Female  
213       3650.0  Female  
176       3300.0  Female  
162       3800.0  Female  
152       3500.0  Female  
180       3700.0  Female  
170       3450.0  Female  
193       3650.0  Female  
158       3250.0  Female  
160       4150.0  Female  
166       3575.0  Female  
214       3650.0  Female  
204       3600.0  Female  
211       3525.0  Female  
195       3500.0  Female  
155       3525.0  Female  
157       3950.0  Female  
208       3250.0  Female  
216       3400.0  Female  
174       2900.0  Female  
184       3350.0  Female  
206       3350.0  Female  
172       3600.0  Female  
182       3200.0  Female

In [29]:
# species(종)별 성별 구분하여 평균 몸무게 출력
# => ex) Adelie, Female / Adelie, male / Gentoo, Female...

In [37]:
dfc.value_counts('species')

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [38]:
dfc.value_counts('sex')

sex
Male      168
Female    165
Name: count, dtype: int64

In [44]:
cond_a = dfc['species'] == 'Adelie'
cond_g = dfc['species'] == 'Gentoo'
cond_c = dfc['species'] == 'Chinstrap'

cond_m = dfc['sex'] == 'Male'
cond_f = dfc['sex'] == 'Female'

print(dfc.loc[(cond_a & cond_m), 'body_mass_g'].mean())
print(dfc.loc[(cond_a & cond_f), 'body_mass_g'].mean())
print(dfc.loc[(cond_g & cond_m), 'body_mass_g'].mean())
print(dfc.loc[(cond_g & cond_f), 'body_mass_g'].mean())
print(dfc.loc[(cond_c & cond_m), 'body_mass_g'].mean())
print(dfc.loc[(cond_c & cond_f), 'body_mass_g'].mean())

4043.4931506849316
3368.8356164383563
5484.836065573771
4679.741379310345
3938.970588235294
3527.205882352941


In [45]:
# bill_depth 결측치 채우기
# => 같은종 같은섬의 평균으로

In [48]:
dfc['bill_depth_mm'].isna().sum()

np.int64(2)

In [52]:
dfc.sort_values('bill_depth_mm')

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
244  Gentoo     Biscoe            42.9           13.1              215.0   
220  Gentoo     Biscoe            46.1           13.2              211.0   
268  Gentoo     Biscoe            44.9           13.3              213.0   
228  Gentoo     Biscoe            43.3           13.4              209.0   
225  Gentoo     Biscoe            46.5           13.5              210.0   
..      ...        ...             ...            ...                ...   
13   Adelie  Torgersen            38.6           21.2              191.0   
49   Adelie      Dream            42.3           21.2              191.0   
19   Adelie  Torgersen            46.0           21.5              194.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
339  Gentoo     Biscoe             NaN            NaN                NaN   

     body_mass_g     sex  
244       5000.0  Female  
220       4500.0  Female  
268       5100.0  Female  
228       4400.0  Female  
225       4550.0  Female  
..           ...     ...  
13        3800.0    Male  
49        4150.0    Male  
19        4200.0    Male  
3            NaN     NaN  
339          NaN     NaN  

[344 rows x 7 columns]

In [68]:
cond_a = dfc['species'] == 'Adelie'
cond_g = dfc['species'] == 'Gentoo'

cond_t = dfc['island'] == 'Torgersen'
cond_b = dfc['island'] == 'Biscoe'

print(dfc.loc[(cond_a & cond_t), 'bill_depth_mm'].mean())
print(dfc.loc[(cond_g & cond_b), 'bill_depth_mm'].mean())

dfc_at = dfc.loc[(cond_a & cond_t), 'bill_depth_mm']
dfc_gb = dfc.loc[(cond_g & cond_b), 'bill_depth_mm']

at_mean = dfc.loc[(cond_a & cond_t), 'bill_depth_mm'].mean()
gb_mean = dfc.loc[(cond_g & cond_b), 'bill_depth_mm'].mean()



# dfc_at = dfc_at.fillna(at_mean)
dfc.loc[(cond_g & cond_b), 'bill_depth_mm'] = dfc_gb.fillna(gb_mean)

# dfc.sort_values('bill_depth_mm')
dfc

nan
14.982113821138212


species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1            NaN              181.0   
1    Adelie  Torgersen            39.5            NaN              186.0   
2    Adelie  Torgersen            40.3            NaN              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7            NaN              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN      14.982114                NaN   
340  Gentoo     Biscoe            46.8      14.300000              215.0   
341  Gentoo     Biscoe            50.4      15.700000              222.0   
342  Gentoo     Biscoe            45.2      14.800000              212.0   
343  Gentoo     Biscoe            49.9      16.100000              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
3            NaN     NaN  
4         3450.0  Female  
..           ...     ...  
339          NaN     NaN  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[344 rows x 7 columns]

In [63]:
dfc.loc[(cond_a & cond_t), 'bill_depth_mm'] = dfc.loc[(cond_a & cond_t), 'bill_depth_mm'].fillna(at_mean)
dfc.sort_values('bill_depth_mm')

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
244  Gentoo     Biscoe            42.9           13.1              215.0   
220  Gentoo     Biscoe            46.1           13.2              211.0   
268  Gentoo     Biscoe            44.9           13.3              213.0   
228  Gentoo     Biscoe            43.3           13.4              209.0   
225  Gentoo     Biscoe            46.5           13.5              210.0   
..      ...        ...             ...            ...                ...   
14   Adelie  Torgersen            34.6           21.1              198.0   
13   Adelie  Torgersen            38.6           21.2              191.0   
49   Adelie      Dream            42.3           21.2              191.0   
19   Adelie  Torgersen            46.0           21.5              194.0   
339  Gentoo     Biscoe             NaN            NaN                NaN   

     body_mass_g     sex  
244       5000.0  Female  
220       4500.0  Female  
268       5100.0  Female  
228       4400.0  Female  
225       4550.0  Female  
..           ...     ...  
14        4400.0    Male  
13        3800.0    Male  
49        4150.0    Male  
19        4200.0    Male  
339          NaN     NaN  

[344 rows x 7 columns]

In [70]:
dfc.describe()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     292.000000         342.000000   342.000000
mean        43.921930      16.920487         200.915205  4201.754386
std          5.459584       1.984446          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.100000         190.000000  3550.000000
50%         44.450000      17.050000         197.000000  4050.000000
75%         48.500000      18.600000         213.000000  4750.000000
max         59.600000      21.200000         231.000000  6300.000000

In [73]:
dfc.describe(include='object')

species  island   sex
count      344     344   333
unique       3       3     2
top     Adelie  Biscoe  Male
freq       152     168   168

In [75]:
dfc.count()

species              344
island               344
bill_length_mm       342
bill_depth_mm        292
flipper_length_mm    342
body_mass_g          342
sex                  333
dtype: int64

In [77]:
dfc = df.copy()

In [79]:
dfc['bill_depth_mm'].count()

np.int64(342)

In [80]:
dfc.count()

species              344
island               344
bill_length_mm       342
bill_depth_mm        342
flipper_length_mm    342
body_mass_g          342
sex                  333
dtype: int64

In [84]:
dfc.mean(numeric_only=True)

bill_length_mm         43.921930
bill_depth_mm          17.151170
flipper_length_mm     200.915205
body_mass_g          4201.754386
dtype: float64

In [85]:
dfc['body_mass_g'].agg(['max', 'min', 'count'])

max      6300.0
min      2700.0
count     342.0
Name: body_mass_g, dtype: float64

In [86]:
dfc['species'].mode()

0    Adelie
Name: species, dtype: object

In [88]:
dfc.corr(numeric_only=True)

bill_length_mm  bill_depth_mm  flipper_length_mm  \
bill_length_mm           1.000000      -0.235053           0.656181   
bill_depth_mm           -0.235053       1.000000          -0.583851   
flipper_length_mm        0.656181      -0.583851           1.000000   
body_mass_g              0.595110      -0.471916           0.871202   

                   body_mass_g  
bill_length_mm        0.595110  
bill_depth_mm        -0.471916  
flipper_length_mm     0.871202  
body_mass_g           1.000000

In [90]:
dfc.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [92]:
dfc.notnull().sum()

species              344
island               344
bill_length_mm       342
bill_depth_mm        342
flipper_length_mm    342
body_mass_g          342
sex                  333
dtype: int64

In [93]:
dfc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB
